#!/usr/bin/env bash

if [ -n "$VIRTUAL_ENV" ]; then
  PYTHON="$VIRTUAL_ENV/bin/python"
else
  PYTHON="python3"
fi

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

$PYTHON "$SCRIPT_DIR/src/maestro.py" "$@"
