apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: openai_test_mcp_ollama
  labels:
    app: testapp_mcp_ollama
spec:
  template:
    metadata:
      labels:
        app: testapp_mcp_ollama
    agents:
      - openai_test_ollama
    prompt: | 
      What tools do you have access to? Include all kinds of different types of tools? Print
      out as much information about them as you can, but you MUST also include the text "Tools found [nnn]: 
      followed by a list of exact tool names only, all on a single line. Replace nnn with the number of tools found.
    steps:
      - name: begin
        agent: openai_test_mcp_ollama