apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: meta_agent_workflow
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: meta_agent_workflow
      labels:
        project: maestro-demo
    agents:
      - NLP Agent Planner
      - Format Input Agent
      - Create Agent YAML
    prompt: I want to compare the current weather with the historical averages. To do this, I probably will need 2 agents, one to retrieve the weather and one to compare to the historical average.
    steps:
      - name: NLP Agent Planner
        agent: NLP Agent Planner
      - name: input
        input:
          prompt: |
                  number of agents: 2
                  agent1: weather_fetcher – Retrieves weather data for a given location using OpenMeteo tool. 
                  agent2: temperature_comparator – Compares the retrieved temperature with historical averages using OpenMeteo tool.
          template: "{CONNECTOR}"
      - name: Format Input
        agent: Format Input Agent
      - name: Create Agent YAML
        agent: Create Agent YAML