apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: maestro-deployment
  labels:
    app: mas-example
spec:
  strategy:
    type: condition
    output: nonal
  template:
    metadata:
      labels:
        app: mas-example
    agents:
      - current-affairs
      - hot-or-not
      - cold-activities
      - hot-activities
    prompt: New York City
    steps:
      - name: current-affairs
        agent: current-affairs
        condition: 
        - case: (input.find('hotter') != -1)
          do: hot-activities
        - default: cold-activities
      - name: hot-or-not
        agent: hot-or-not
        condition:
        - if: (input.find('hotter') != -1)
          do: hot-activities
          else: cold-activities