name: Maestro Build and Upload Images

on:
  push:
    tags:
      - "v*"

jobs:
  build-upload:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
    outputs:
      version: ${{ steps.build_push.outputs.version }}
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv and activate the environment
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - name: Build Maestro
        run: uv build
      - name: get docker-compatible GITHUB_ORG
        run: |
          echo "GITHUB_ORG=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Build and push the image
        id: build_push
        run : |
          VERSION=$(grep -E '^(version|tool\.poetry\.version) *= *"[^"]+"' "pyproject.toml" | \
            head -n 1 | \
            sed -E 's/.*"([^"]+)".*/\1/')
          uv run tools/buildimg.sh
          docker tag ghcr.io/$GITHUB_ORG/maestro:$VERSION ghcr.io/$GITHUB_ORG/maestro:$VERSION-${{ matrix.arch }}
          docker tag ghcr.io/$GITHUB_ORG/maestro-cli:$VERSION ghcr.io/$GITHUB_ORG/maestro-cli:$VERSION-${{ matrix.arch }}
          docker push ghcr.io/$GITHUB_ORG/maestro:$VERSION-${{ matrix.arch }}
          docker push ghcr.io/$GITHUB_ORG/maestro-cli:$VERSION-${{ matrix.arch }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
  upload-manifest:
    needs: build-upload
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get docker-compatible GITHUB_ORG
        run: |
          echo "GITHUB_ORG=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Push multiarch image to ghcr.io
        run: |
          docker manifest create ghcr.io/$GITHUB_ORG/maestro:${{ needs.build-upload.outputs.version }} \
            --amend ghcr.io/$GITHUB_ORG/maestro:${{ needs.build-upload.outputs.version }}-x86_64 \
            --amend ghcr.io/$GITHUB_ORG/maestro:${{ needs.build-upload.outputs.version }}-arm64 &&
          docker manifest create ghcr.io/$GITHUB_ORG/maestro-cli:${{ needs.build-upload.outputs.version }} \
            --amend ghcr.io/$GITHUB_ORG/maestro:${{ needs.build-upload.outputs.version }}-x86_64 \
            --amend ghcr.io/$GITHUB_ORG/maestro:${{ needs.build-upload.outputs.version }}-arm64 &&
          docker manifest push ghcr.io/$GITHUB_ORG/maestro:${{ needs.build-upload.outputs.version }}
          docker manifest push ghcr.io/$GITHUB_ORG/maestro-cli:${{ needs.build-upload.outputs.version }}